# Generated by Django 3.2 on 2023-05-10 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='sex',
            field=models.CharField(blank=True, choices=[('MAN', 'Man'), ('WOMAN', 'Woman')], default=None, max_length=10, null=True),
        ),
    ]
